/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST3;

/**
 *
 * @author Yglx
 */
public class POSTTEST3 extends javax.swing.JFrame {

    /**
     * Creates new form POSTTEST3
     */
    public POSTTEST3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pIsi = new javax.swing.JPanel();
        pProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pInformasi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pAbout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pHeader = new javax.swing.JPanel();
        jDinas = new javax.swing.JLabel();
        jPemerintah = new javax.swing.JLabel();
        jSamarinda = new javax.swing.JLabel();
        jMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnKTP = new javax.swing.JButton();
        btnInformasi = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();
        pFooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pIsi.setBackground(new java.awt.Color(217, 217, 255));
        pIsi.setLayout(new java.awt.CardLayout());

        pProfile.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTTEST3/test.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));

        jLabel4.setText("Kantor Gubernur Kalimantan Timur");

        jLabel5.setText("Visi Misi kami adalah mempermudah segala pelayanan publik");

        pHome.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang di Aplikasi Dinas Kependudukan dan Pencatatan Sipil");

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pProfileLayout = new javax.swing.GroupLayout(pProfile);
        pProfile.setLayout(pProfileLayout);
        pProfileLayout.setHorizontalGroup(
            pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileLayout.createSequentialGroup()
                .addGroup(pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pProfileLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pProfileLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(89, 89, 89)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pProfileLayout.setVerticalGroup(
            pProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pIsi.add(pProfile, "card5");

        pInformasi.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Menu Ini Masih Kosong");

        javax.swing.GroupLayout pInformasiLayout = new javax.swing.GroupLayout(pInformasi);
        pInformasi.setLayout(pInformasiLayout);
        pInformasiLayout.setHorizontalGroup(
            pInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInformasiLayout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(308, 308, 308))
        );
        pInformasiLayout.setVerticalGroup(
            pInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformasiLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(191, 191, 191))
        );

        pIsi.add(pInformasi, "card6");

        pAbout.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Menu Ini Masih Kosong");

        javax.swing.GroupLayout pAboutLayout = new javax.swing.GroupLayout(pAbout);
        pAbout.setLayout(pAboutLayout);
        pAboutLayout.setHorizontalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
            .addGroup(pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pAboutLayout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addComponent(jLabel7)
                    .addContainerGap(768, Short.MAX_VALUE)))
        );
        pAboutLayout.setVerticalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pAboutLayout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jLabel7)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        pIsi.add(pAbout, "card7");

        getContentPane().add(pIsi, java.awt.BorderLayout.CENTER);

        pHeader.setBackground(new java.awt.Color(0, 0, 0));

        jDinas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDinas.setForeground(new java.awt.Color(255, 255, 255));
        jDinas.setText("DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL");

        jPemerintah.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPemerintah.setForeground(new java.awt.Color(255, 255, 255));
        jPemerintah.setText("PEMERINTAH");

        jSamarinda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSamarinda.setForeground(new java.awt.Color(255, 255, 255));
        jSamarinda.setText("KOTA SAMARINDA");

        jMenu.setLayout(new java.awt.GridLayout(1, 0));

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.setBorderPainted(false);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jMenu.add(btnHome);

        btnProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jMenu.add(btnProfile);

        btnKTP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKTP.setText("Buat KTP");
        btnKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKTPActionPerformed(evt);
            }
        });
        jMenu.add(btnKTP);

        btnInformasi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInformasi.setText("Informasi");
        btnInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformasiActionPerformed(evt);
            }
        });
        btnInformasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInformasiKeyPressed(evt);
            }
        });
        jMenu.add(btnInformasi);

        btnAbout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        btnAbout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAboutKeyPressed(evt);
            }
        });
        jMenu.add(btnAbout);

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTTEST3/Logo_Kota_Samarinda2.png"))); // NOI18N

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPemerintah)
                    .addComponent(jDinas)
                    .addComponent(jSamarinda))
                .addGap(0, 771, Short.MAX_VALUE))
            .addComponent(jMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pHeaderLayout.createSequentialGroup()
                        .addComponent(jDinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPemerintah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSamarinda))
                    .addComponent(jLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pHeader, java.awt.BorderLayout.PAGE_START);

        pFooter.setBackground(new java.awt.Color(0, 0, 0));
        pFooter.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        getContentPane().add(pFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKTPActionPerformed
        new ktp().setVisible(true); // mengambil dari ktp.java kemudian aksinya apabila di klik btnKtp akan tertampil form ktp.java
    }//GEN-LAST:event_btnKTPActionPerformed

    private void btnInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformasiActionPerformed
        // TODO add your handling code here:
        pInformasi.setVisible(true);
    }//GEN-LAST:event_btnInformasiActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        pAbout.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        pHome.setVisible(true);// set apabila btnHome di pencet maka akan tertampil panel Home / pHome
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnInformasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInformasiKeyPressed
        pInformasi.setVisible(true);// set apabila btnInformasi di pencet maka akan tertampil panel Informasi / pInformasi
    }//GEN-LAST:event_btnInformasiKeyPressed

    private void btnAboutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAboutKeyPressed
        // TODO add your handling code here:
        pAbout.setVisible(true);// set apabila btnAbout di pencet maka akan tertampil panel About / pAbout
        
    }//GEN-LAST:event_btnAboutKeyPressed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSTTEST3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInformasi;
    private javax.swing.JButton btnKTP;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jDinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jMenu;
    private javax.swing.JLabel jPemerintah;
    private javax.swing.JLabel jSamarinda;
    private javax.swing.JPanel pAbout;
    private javax.swing.JPanel pFooter;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pInformasi;
    private javax.swing.JPanel pIsi;
    private javax.swing.JPanel pProfile;
    // End of variables declaration//GEN-END:variables
}
